version: '3'
services:
  db:
    image: postgres:latest
    container_name: my_postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin      # Remplacez par le nom d'utilisateur souhaité
      POSTGRES_PASSWORD: adminpwd  # Remplacez par le mot de passe souhaité
      POSTGRES_DB: db   # Remplacez par le nom de la base de données souhaité
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d db"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: my_api
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      DATABASE_URL : "postgres://admin:adminpwd@db:5432/db"
    depends_on:
      db:
        condition: service_healthy
    
volumes:
  postgres_data:


# psql -h localhost -p 5432 -U admin -d db
